#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Every path below is relative to the repository root, and the wizard writes
# files there. Move rather than scatter snapshots wherever it was invoked from.
cd "$(dirname "$0")/.."

DOMAIN="${DOMAIN:-10bitlabs.co.uk}"
SNAPSHOT_DIR="docs/dns"
TODAY="$(date +%F)"
SNAPSHOT_TMP="$(mktemp)"
trap 'rm -f "$SNAPSHOT_TMP"' EXIT

# Facts about the zone, read fresh so the wizard can tell you what is already
# true instead of asking you to remember. Everything here is a read.
current_ns() { dig +short NS "$DOMAIN" | sed 's/\.$//' | sort | tr '\n' ' '; }
on_cloudflare() { [[ "$(current_ns)" == *ns.cloudflare.com* ]]; }

TOTAL_STAGES=7

banner "10 Bit Labs — domain cutover"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Export the record set before anything changes"
say "The zone carries a working mailbox. Before any change, capture what it"
say "holds — a rollback you cannot describe is not a rollback."
say ""
say "First, the automatic witness — what the nameservers answer right now:"
# Via a temp file: a redirect truncates its target before the command runs, and
# the target here is a committed snapshot. A failed re-run must not be able to
# replace the evidence with an empty file.
if ./scripts/dns-snapshot.sh "$DOMAIN" > "$SNAPSHOT_TMP" && [[ -s "$SNAPSHOT_TMP" ]]; then
  mv "$SNAPSHOT_TMP" "$SNAPSHOT_DIR/snapshot-$TODAY.txt"
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$SNAPSHOT_DIR/snapshot-$TODAY.txt"
else
  rm -f "$SNAPSHOT_TMP"
  warn "the snapshot failed — do not continue until you know why"
  SKIPPED+=("DNS snapshot — ./scripts/dns-snapshot.sh")
fi
say ""
say "That is a witness, not an export: it can only ask about names it already"
say "knows, and a proxied record answers with Cloudflare's addresses rather"
say "than its own content. Now take the real export, a BIND file, from"
say "whichever provider currently holds the zone."
if on_cloudflare; then
  note "The zone is on Cloudflare, so Cloudflare holds it."
  open_url "https://dash.cloudflare.com/?to=/:account/$DOMAIN/dns/records"
  step "DNS → Records → Export → 'Export' (this downloads a .txt BIND file)."
else
  note "The zone is still on GoDaddy's nameservers."
  open_url "https://dcc.godaddy.com/control/dnsmanagement?domainName=$DOMAIN"
  step "DNS → Records → the three-dot menu → 'Export' / 'Download zone file'."
fi
step "Move the downloaded file into $SNAPSHOT_DIR/ and commit it."
note "GoDaddy keeps its own copy of the zone even after you delegate away, so"
note "this export stays available — but take it now anyway."
pause "Press Enter once the export is saved"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Recreate every record at Cloudflare — mail first"
say "The nameserver switch is only safe once Cloudflare's copy of the zone is"
say "complete. A missing MX record does not fail loudly; senders just get"
say "bounces you never see."
say ""
say "All five mail records must exist at Cloudflare BEFORE stage 3:"
step "MX   @                  mx01.mail.icloud.com    priority 10"
step "MX   @                  mx02.mail.icloud.com    priority 10"
step "TXT  @                  v=spf1 include:icloud.com ~all"
step "TXT  @                  apple-domain=…          (from iCloud settings)"
step "CNAME sig1._domainkey   sig1.dkim.$DOMAIN.at.icloudmailadmin.com"
say ""
warn "sig1._domainkey must be DNS only — grey cloud, never orange."
note "Proxied, Cloudflare answers that name with its own addresses instead of"
note "following the CNAME. Mail still flows and SPF still passes; only the"
note "signature quietly fails, which is the kind of breakage nobody notices."
say ""
warn "Do NOT enable Cloudflare Email Routing, at any point."
note "It installs its own MX records and takes delivery away from iCloud. The"
note "dashboard will suggest it; decline. See docs/dns/README.md."
say ""
note "There is one DKIM record. Apple publishes sig1 only — there is no sig2,"
note "and looking for one wastes an afternoon."
open_url "https://dash.cloudflare.com/?to=/:account/$DOMAIN/dns/records"
pause "Press Enter once every record from the stage 1 export exists at Cloudflare"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Point the nameservers at Cloudflare"
if on_cloudflare; then
  printf '  %s✓%s Already delegated — nothing to do here.\n' "$GREEN" "$RESET"
  note "$(current_ns)"
  pause "Press Enter to continue"
else
  say "This is the irreversible-looking step, and the only one that can break"
  say "something already in use. It is also genuinely reversible — see the"
  say "rollback section of docs/dns/README.md before you start."
  say ""
  say "Cloudflare showed you two nameservers when you created the zone. They"
  say "are the pair to enter at GoDaddy."
  open_url "https://dcc.godaddy.com/control/dnsmanagement?domainName=$DOMAIN"
  step "Domain → Nameservers → Change → 'I'll use my own nameservers'."
  step "Enter both Cloudflare nameservers, and remove GoDaddy's."
  step "Save."
  note "Delegation usually takes minutes; allow up to 24 hours."
  if confirm "Have you changed the nameservers at GoDaddy?"; then
    say "Waiting for the delegation to appear…"
    for _ in 1 2 3 4 5 6; do
      on_cloudflare && break
      sleep 10
    done
    if on_cloudflare; then
      printf '  %s✓%s Delegated: %s\n' "$GREEN" "$RESET" "$(current_ns)"
    else
      warn "not visible yet — that is normal. Re-run this wizard later."
      SKIPPED+=("confirm the nameserver delegation has propagated")
    fi
  else
    SKIPPED+=("the GoDaddy nameserver change — nothing after this stage works without it")
  fi
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Prove the mailbox still works — both directions"
say "This is the stage the whole cutover exists to protect, and the only one"
say "with no automated substitute. Do not skip it."
note "It comes before the site stages on purpose. Everything after this rewrites"
note "the apex record; if mail is going to break, the cheapest moment to find"
note "out is now, with nothing else in between to blame."
say ""
say "First, the dashboard switch the record checks cannot see:"
open_url "https://dash.cloudflare.com/?to=/:account/$DOMAIN/email/routing"
step "Confirm Email Routing is NOT enabled."
note "The verify script proves no Cloudflare mail exchanger is published, which"
note "is what actually decides delivery — but Email Routing can be enabled and"
note "unconfigured, and only this page shows that. Decline any offer to enable it."
if confirm "Is Email Routing disabled?"; then
  printf '  %s✓%s Email Routing is off.\n' "$GREEN" "$RESET"
else
  SKIPPED+=("disable Cloudflare Email Routing — it will take delivery from iCloud")
  warn "disable it before going further"
fi
say ""
step "From a mailbox that is NOT the iCloud one, send a message to hello@$DOMAIN."
step "Confirm it arrives. That proves inbound delivery and the MX records."
say ""
step "From hello@$DOMAIN, send a message to a Gmail address you control."
step "In Gmail, open it → three dots → 'Show original'."
step "Confirm SPF: PASS and DKIM: PASS."
note "Inbound working does not imply outbound is signed correctly. A proxied"
note "DKIM record breaks only the signature, and only the recipient sees it."
say ""
say "If iCloud reports the domain as unverified, re-verify it there:"
open_url "https://www.icloud.com/settings/"
step "iCloud settings → Custom Email Domain → your domain → re-check records."
note "Apple may issue a new apple-domain= value; if it does, update the TXT"
note "record at Cloudflare and re-run ./scripts/verify-cutover.sh."
if confirm "Did a test message ARRIVE at hello@$DOMAIN?"; then
  printf '  %s✓%s Inbound mail confirmed.\n' "$GREEN" "$RESET"
else
  SKIPPED+=("inbound mail test — the cutover is NOT done until this passes")
  warn "consider rolling back the nameservers — docs/dns/README.md"
fi
if confirm "Did a message SENT from hello@$DOMAIN pass SPF and DKIM?"; then
  printf '  %s✓%s Outbound mail confirmed.\n' "$GREEN" "$RESET"
else
  SKIPPED+=("outbound mail test — check sig1._domainkey is DNS only, not proxied")
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Bind the apex to the Worker"
say "The apex becomes a Worker Custom Domain: Cloudflare writes the apex record"
say "and issues the certificate for it."
note "This touches the apex record only. It does not touch MX, SPF, DKIM or the"
note "Apple verification record — the mailbox is not in its path."
say ""
note "It is not declared in wrangler.jsonc on purpose: as a route it makes"
note "wrangler dev serve every local request as the apex, and the test that a"
note "preview hostname is non-indexable stops describing production."
say ""
if [[ -f "$ENV_FILE" ]]; then
  set -a; . "$ENV_FILE"; set +a
  note "Credentials loaded from $ENV_FILE."
else
  warn "no $ENV_FILE — run ./scripts/setup-deploy.sh first."
fi
say "The site itself must be deployed before the domain can point at it."
if confirm "Build and deploy the Worker now?"; then
  if npm run build && npx --yes wrangler deploy; then
    printf '  %s✓%s Deployed.\n' "$GREEN" "$RESET"
  else
    warn "the deploy failed"
    SKIPPED+=("deploy the Worker — 'npm run build && npx wrangler deploy'")
  fi
fi
say ""
say "Now the binding. The deploy token came from the 'Edit Cloudflare Workers'"
say "template, which does not carry DNS permissions, so this may need the"
say "dashboard instead — the wizard tries the API first and tells you either way."
BOUND=0
if [[ -n "${CLOUDFLARE_API_TOKEN:-}" && -n "${CLOUDFLARE_ACCOUNT_ID:-}" ]] && confirm "Bind $DOMAIN to the Worker via the API?"; then
  # The zone id is the first 32-hex id in the response; grep -o rather than a
  # greedy sed, which would walk past it to the account id further along.
  ZONE_ID=$(curl -sS -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    "https://api.cloudflare.com/client/v4/zones?name=$DOMAIN" \
    | grep -o '"id":"[0-9a-f]\{32\}"' | head -n1 | cut -d'"' -f4 || true)
  if [[ -z "$ZONE_ID" ]]; then
    warn "could not read the zone id — the token may not have Zone:Read"
  else
    RESPONSE=$(curl -sS -X PUT \
      -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
      -H "Content-Type: application/json" \
      "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/workers/domains" \
      --data "{\"environment\":\"production\",\"hostname\":\"$DOMAIN\",\"service\":\"10bitlabs-site\",\"zone_id\":\"$ZONE_ID\"}")
    if printf '%s' "$RESPONSE" | grep -q '"success":true'; then
      printf '  %s✓%s The apex is bound to the Worker.\n' "$GREEN" "$RESET"
      BOUND=1
    else
      warn "the API refused the binding:"
      note "$RESPONSE"
    fi
  fi
fi
if (( ! BOUND )); then
  say "Bind it in the dashboard instead:"
  open_url "https://dash.cloudflare.com/?to=/:account/workers/services/view/10bitlabs-site/production/settings"
  step "Settings → Domains & Routes → Add → Custom Domain."
  step "Enter $DOMAIN (the apex, with no www) and add it."
  note "Cloudflare will say it is replacing the existing apex record. That is"
  note "expected — the record it replaces is the one serving nothing today."
  pause "Press Enter once the Custom Domain shows as active"
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Redirect www to the apex"
say "www is deliberately not a Worker route. Bound as one it would serve the"
say "site, and the site would have two hostnames that both look canonical."
say "Instead it stays a proxied record and the zone 301s it to the apex."
say ""
say "First, the record — www must be proxied for a redirect rule to see it:"
open_url "https://dash.cloudflare.com/?to=/:account/$DOMAIN/dns/records"
step "Ensure www exists as a CNAME to $DOMAIN, with the orange cloud ON."
say ""
say "Then the rule:"
open_url "https://dash.cloudflare.com/?to=/:account/$DOMAIN/rules/redirect-rules"
step "Create rule → name it 'www to apex'."
step "If: Hostname equals www.$DOMAIN"
step "Then: Dynamic redirect, status 301, expression:"
note "    concat(\"https://$DOMAIN\", http.request.uri.path)"
step "Tick 'Preserve query string'. Deploy the rule."
note "301 rather than 302 on purpose: a permanent redirect consolidates search"
note "signals onto the apex, which is the point of having one canonical host."
pause "Press Enter once the rule is deployed"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify everything checkable from outside"
say "One command asserts the delegation, all five mail records, the absence of"
say "Cloudflare Email Routing, the apex, the www redirect and the preview host."
say ""
if ./scripts/verify-cutover.sh "$DOMAIN"; then
  say "Take a closing snapshot so the after state is committed alongside the before:"
  if ./scripts/dns-snapshot.sh "$DOMAIN" > "$SNAPSHOT_TMP" && [[ -s "$SNAPSHOT_TMP" ]]; then
    mv "$SNAPSHOT_TMP" "$SNAPSHOT_DIR/snapshot-$TODAY-after.txt"
    printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$SNAPSHOT_DIR/snapshot-$TODAY-after.txt"
  else
    rm -f "$SNAPSHOT_TMP"
    warn "the closing snapshot failed"
  fi
else
  warn "some checks failed — the cutover is not done"
  SKIPPED+=("./scripts/verify-cutover.sh — re-run until it passes")
fi
pause "Press Enter to finish"

finish
