#!/usr/bin/env bash
#
# Snapshot the zone as the public internet currently sees it.
#
# Queries the domain's own authoritative nameservers rather than a local
# resolver, so the answer is the zone itself and not a cached copy of it. The
# output is committed, so a later "did the cutover change anything?" is a diff
# rather than a memory.
#
# This is a *witness*, not the authoritative export. dig can only ask for names
# it already knows, so a label nobody thought to list here is invisible to it.
# The complete export is the BIND file downloaded from the DNS provider — see
# docs/dns/README.md.
#
#   ./scripts/dns-snapshot.sh [domain] > docs/dns/snapshot-$(date +%F).txt

set -euo pipefail

DOMAIN="${1:-10bitlabs.co.uk}"

# Labels worth asking about: the ones this zone is known to carry, plus the
# handful a registrar or a mail provider tends to leave lying around.
LABELS=(
  www mail ftp autodiscover autoconfig
  _dmarc _domainconnect _acme-challenge
  # sig1 is the mailbox's only DKIM key. sig2 is probed precisely because it
  # should never answer: a plan draft once claimed two keys, and a snapshot that
  # asks is a snapshot that can disprove it.
  sig1._domainkey sig2._domainkey
)

command -v dig >/dev/null 2>&1 || { echo "dig is required" >&2; exit 1; }

# Ask a nameserver that is authoritative for the zone, so the records come from
# the zone rather than from whatever a resolver happens to be holding.
# Read into an array the long way round: macOS ships bash 3.2, which has no
# mapfile.
NAMESERVERS=()
while IFS= read -r ns; do
  [[ -n "$ns" ]] && NAMESERVERS+=("$ns")
done < <(dig +short NS "$DOMAIN" | sed 's/\.$//' | sort)
[[ ${#NAMESERVERS[@]} -gt 0 ]] || { echo "No NS records for $DOMAIN" >&2; exit 1; }
AUTH="${NAMESERVERS[0]}"

# records NAME TYPE — one name's answers, straight from the authoritative server.
records() { dig +noall +answer "@$AUTH" "$2" "$1" | sed 's/[[:space:]]\+/ /g' | sort; }

echo "; DNS snapshot of $DOMAIN"
echo "; taken $(date -u '+%Y-%m-%dT%H:%M:%SZ') against authoritative $AUTH"
echo "; generated by scripts/dns-snapshot.sh — see docs/dns/README.md"
echo ";"
echo "; Authoritative nameservers:"
printf ';   %s\n' "${NAMESERVERS[@]}"
echo

for type in SOA NS A AAAA MX TXT CAA; do
  records "$DOMAIN" "$type"
done

# A label that is a CNAME answers every type with the same CNAME line, so the
# whole block is deduplicated rather than each query.
for label in "${LABELS[@]}"; do
  for type in A AAAA CNAME MX TXT; do
    records "$label.$DOMAIN" "$type"
  done
done | sort -u
