// Writes dist/_headers after the Astro build.
//
// The CSP admits the blocking theme script by hash rather than by opening up
// 'unsafe-inline', so the hash has to be computed from the bytes that actually
// shipped. Hashing the built HTML rather than the source means a stray edit to
// the script cannot silently break the page — the hash simply follows it.
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import astroConfig from '../astro.config.mjs';

const DIST = 'dist';
// One source for the canonical hostname: if the site moves, the header rule that
// decides what is indexable moves with it rather than silently pointing at the
// old apex.
const APEX = new URL(astroConfig.site).origin;

async function htmlFiles(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await htmlFiles(path)));
    else if (entry.name.endsWith('.html')) found.push(path);
  }
  return found;
}

const hashes = new Set();
for (const file of await htmlFiles(DIST)) {
  const html = await readFile(file, 'utf8');
  for (const [, attrs, body] of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)) {
    if (/\ssrc=/.test(attrs)) continue;
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
}

if (hashes.size === 0) throw new Error('No inline script found — the theme script should be there.');
if (hashes.size > 1) {
  throw new Error(
    `Expected exactly one inline script, found ${hashes.size}. The theme script is meant to be the only one.`
  );
}

const csp = [
  "default-src 'none'",
  `script-src 'self' ${[...hashes].join(' ')}`,
  "style-src 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'"
].join('; ');

// X-Robots-Tag is set for everything and detached on the apex, so any hostname
// that is not the canonical site — a workers.dev preview, a local build — is
// non-indexable by default rather than by remembering to add a rule.
const headers = `# Generated by scripts/emit-headers.mjs — do not edit by hand.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  X-Robots-Tag: noindex

${APEX}/*
  ! X-Robots-Tag

/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  Cache-Control: public, max-age=31536000, immutable
`;

await writeFile(join(DIST, '_headers'), headers);
console.log(`[headers] wrote ${DIST}/_headers with script hash ${[...hashes][0]}`);
