// Downloads the two typefaces from Google Fonts into public/fonts/ and writes
// src/styles/fonts.css. Run once, or again to refresh; the site never talks to
// Google at runtime — that is the point of vendoring these files.
import { mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Only the weights the design uses, only latin + latin-ext. latin alone omits
// U+0130 (İ) and would break the studio's own Turkish product names.
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap';
const WANTED_SUBSETS = new Set(['latin', 'latin-ext']);

const SLUGS = { 'Space Grotesk': 'space-grotesk', 'JetBrains Mono': 'jetbrains-mono' };

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => r.text());

const faces = [...css.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]*\})/g)]
  .map(([, subset, face]) => ({
    subset,
    family: /font-family: '([^']+)'/.exec(face)[1],
    weight: Number(/font-weight: (\d+)/.exec(face)[1]),
    url: /src: url\((\S+)\)/.exec(face)[1],
    unicodeRange: /unicode-range: ([^;]+);/.exec(face)[1]
  }))
  .filter((f) => WANTED_SUBSETS.has(f.subset));

// Google serves one variable file per family+subset covering the whole requested
// weight range, so the three weights of each family are the same bytes. Ship it
// once and declare the range, rather than three identical downloads.
const groups = new Map();
for (const f of faces) {
  const key = `${f.family}|${f.subset}`;
  const g = groups.get(key) ?? { ...f, weights: [] };
  g.weights.push(f.weight);
  groups.set(key, g);
}

await mkdir('public/fonts', { recursive: true });
await mkdir('src/styles', { recursive: true });

const rules = [];
for (const g of groups.values()) {
  const bytes = Buffer.from(await fetch(g.url).then((r) => r.arrayBuffer()));
  const file = `${SLUGS[g.family]}-${g.subset}.woff2`;
  await writeFile(`public/fonts/${file}`, bytes);

  const min = Math.min(...g.weights);
  const max = Math.max(...g.weights);
  rules.push(
    `@font-face {\n  font-family: '${g.family}';\n  font-style: normal;\n  font-weight: ${min} ${max};\n  font-display: swap;\n  src: url('/fonts/${file}') format('woff2');\n  unicode-range: ${g.unicodeRange};\n}`
  );
  console.log(
    `${file}  ${bytes.byteLength} bytes  weights ${min}-${max}  sha256 ${createHash('sha256').update(bytes).digest('hex').slice(0, 12)}`
  );
}

await writeFile(
  'src/styles/fonts.css',
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n${rules.join('\n\n')}\n`
);
